### ISSUE TITLE
CKAN not working with guzzle

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-ckan-registry#270]
https://github.com/silverstripe/silverstripe-ckan-registry/runs/7419517559?check_suite_focus=true

Failing behat test (also fails manual testing) where the server will send a guzzle request to https://catalogue.data.govt.nz/dataset/directory-of-educational-institutions

This website has imperva in-front of it which intentionally sends back an invalid __utmv header https://stackoverflow.com/a/62407633

Guzzle psr(used by guzzle) throws an exception because of this header https://github.com/guzzle/psr7/blob/1.x/src/MessageTrait.php#L267
```php
        if (! preg_match('/^[\x20\x09\x21-\x7E\x80-\xFF]*$/', $value)) {
            throw new \InvalidArgumentException(sprintf('"%s" is not valid header value', $value));
        }
```

We could also update ckan to use something other than guzzle

**Comment by emteknetnz** [comment]
Issue is not resolved with 4.11 / guzzle 7 - still getting the same failure - https://github.com/silverstripe/silverstripe-ckan-registry/runs/7509511643?check_suite_focus=true#step:12:151

**Comment by andrewandante** [comment]
Ticket currently open with Imperva to disable the cookie that is causing this issue - will update once ticket is closed.

**Comment by andrewandante** [comment]
Ticket has been resolved, can you re-test?

**Comment by GuySartorelli** [comment]
Still failed: https://github.com/silverstripe/silverstripe-ckan-registry/actions/runs/2772250337

**Comment by andrewandante** [comment]
😢 have asked Imperva to check themselves.

**Comment by andrewandante** [comment]
It might be worth adding a config option to force HTTP2 as that seems to be a way around the problem - it would at least get the test to pass. Should be able to pass in like this: https://github.com/guzzle/guzzle/issues/1249#issuecomment-138636488

**Comment by andrewandante** [comment]
I've purged the cache at their request, and it's now working for me locally - once more round the block?

**Comment by GuySartorelli** [comment]
Still failing in CI https://github.com/silverstripe/silverstripe-ckan-registry/actions/runs/2772250337

> "___utmvaEPBuoiEYB=mPnGQzA; path=/; Max-Age=900; Secure; SameSite=None" is not valid header value

**Comment by emteknetnz** [comment]
I've noticed this seems to fail sporadically, though more failures than non-failures - seems that Imperva does not consistently send the malformed header?

**Comment by andrewandante** [comment]
Update: Imperva fix needs to be applied to a different site, not under our control - have engaged the third party responsible, hopefully to be resolved soon 😬
